// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.idl

#pragma once

#include <basic/UUID.hpp>
#include <vector>

namespace cppble {

/** The central interface */
class CentralInterface {
public:
    virtual ~CentralInterface() {}

    virtual void start_scan(const std::vector<cppble::UUID> & uuids) = 0;

    virtual void stop_scan() = 0;
};

}  // namespace cppble
