// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.idl

#include "NativeCentralInterface.hpp"  // my header
#include "Basic-jni.hpp"
#include "Marshal.hpp"

namespace djinni_generated {

NativeCentralInterface::NativeCentralInterface() : ::djinni::JniInterface<::cppble::CentralInterface, NativeCentralInterface>() {}

NativeCentralInterface::~NativeCentralInterface() = default;

NativeCentralInterface::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeCentralInterface::JavaProxy::~JavaProxy() = default;

void NativeCentralInterface::JavaProxy::start_scan(const std::vector<cppble::UUID> & c_uuids) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeCentralInterface>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_startScan,
                           ::djinni::get(::djinni::List<::djinni::UUID>::fromCpp(jniEnv, c_uuids)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeCentralInterface::JavaProxy::stop_scan() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeCentralInterface>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_stopScan);
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
