// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.idl

#include "central_interface.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol YGCentralInterface;

namespace djinni_generated {

class CentralInterface
{
public:
    using CppType = std::shared_ptr<::cppble::CentralInterface>;
    using CppOptType = std::shared_ptr<::cppble::CentralInterface>;
    using ObjcType = id<YGCentralInterface>;

    using Boxed = CentralInterface;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

