// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.idl

#import <Foundation/Foundation.h>


/** The central interface */
@protocol YGCentralInterface

- (void)startScan:(nonnull NSArray<NSUUID *> *)uuids;

- (void)stopScan;

@end
