// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.idl

package net.yageek.cppble;

import java.util.ArrayList;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** The central interface */
/*package*/ abstract class CentralInterface {
    public abstract void startScan(@Nonnull ArrayList<java.util.UUID> uuids);

    public abstract void stopScan();
}
